In [ ]:
import pandas as pd

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("harishyadav0506/impact-of-social-media-on-life")

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/harishyadav0506/impact-of-social-media-on-life/1.archive...

100%|██████████| 77.1k/77.1k [00:00<00:00, 28.3MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/harishyadav0506/impact-of-social-media-on-life/versions/1

In [ ]:
df = pd.read_csv('/content/social_media.csv')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4500 entries, 0 to 4499
Data columns (total 16 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Student_ID                   4500 non-null   object
 1   Age                          4500 non-null   int64
 2   Gender                       4500 non-null   object
 3   Academic_Level               4500 non-null   object
 4   Primary_Platform             4500 non-null   object
 5   Daily_Usage_Hours            4500 non-null   float64
 6   Weekend_Extra_Hours          4500 non-null   float64
 7   Device_Type                  4500 non-null   object
 8   Sleep_Duration_Hours         4500 non-null   float64
 9   Sleep_Quality_Score          4500 non-null   int64
 10  Late_Night_Usage             4500 non-null   bool
 11  Social_Comparison_Frequency  4500 non-null   object
 12  Perceived_Stress_Score       4454 non-null   float64
 13  Mental_Health_Index          4500 non-null   int64
 14  Academic_Performance_GPA     4415 non-null   float64
 15  Overall_Impact               4500 non-null   object
dtypes: bool(1), float64(5), int64(3), object(7)
memory usage: 531.9+ KB

In [ ]:
df.head()

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
0,STU_2024000,19,Female,Undergraduate,Snapchat,7.5,1.5,Smartphone,5.9,2,True,Always,20.0,73,2.73,Neutral
1,STU_2024001,19,Female,Undergraduate,Instagram,4.6,1.3,Smartphone,7.9,3,True,Sometimes,17.0,90,3.21,Beneficial
2,STU_2024002,17,Female,High School,TikTok,10.9,1.7,Smartphone,5.2,1,True,Frequently,18.0,70,3.00,Neutral
3,STU_2024003,16,Female,High School,YouTube,6.0,2.3,Tablet,7.6,4,True,Sometimes,15.0,82,3.42,Beneficial
4,STU_2024004,17,Male,High School,LinkedIn,3.3,2.6,Smartphone,7.6,4,True,Never,16.0,84,3.41,Beneficial

In [ ]:
df['Age'].astype('int8')

0       19
1       19
2       17
3       16
4       17
        ..
4495    16
4496    19
4497    19
4498    16
4499    24
Name: Age, Length: 4500, dtype: int8

In [ ]:
df['Age'] = df['Age'].astype('int8')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4500 entries, 0 to 4499
Data columns (total 16 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Student_ID                   4500 non-null   object
 1   Age                          4500 non-null   int8
 2   Gender                       4500 non-null   object
 3   Academic_Level               4500 non-null   object
 4   Primary_Platform             4500 non-null   object
 5   Daily_Usage_Hours            4500 non-null   float64
 6   Weekend_Extra_Hours          4500 non-null   float64
 7   Device_Type                  4500 non-null   object
 8   Sleep_Duration_Hours         4500 non-null   float64
 9   Sleep_Quality_Score          4500 non-null   int64
 10  Late_Night_Usage             4500 non-null   bool
 11  Social_Comparison_Frequency  4500 non-null   object
 12  Perceived_Stress_Score       4454 non-null   float64
 13  Mental_Health_Index          4500 non-null   int64
 14  Academic_Performance_GPA     4415 non-null   float64
 15  Overall_Impact               4500 non-null   object
dtypes: bool(1), float64(5), int64(2), int8(1), object(7)
memory usage: 501.1+ KB

In [ ]:
df['Sleep_Quality_Score'].astype('int8')

0       2
1       3
2       1
3       4
4       4
       ..
4495    3
4496    3
4497    2
4498    3
4499    3
Name: Sleep_Quality_Score, Length: 4500, dtype: int8

In [ ]:
df['Sleep_Quality_Score'] = df['Sleep_Quality_Score'].astype('int8')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4500 entries, 0 to 4499
Data columns (total 16 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Student_ID                   4500 non-null   object
 1   Age                          4500 non-null   int8
 2   Gender                       4500 non-null   object
 3   Academic_Level               4500 non-null   object
 4   Primary_Platform             4500 non-null   object
 5   Daily_Usage_Hours            4500 non-null   float64
 6   Weekend_Extra_Hours          4500 non-null   float64
 7   Device_Type                  4500 non-null   object
 8   Sleep_Duration_Hours         4500 non-null   float64
 9   Sleep_Quality_Score          4500 non-null   int8
 10  Late_Night_Usage             4500 non-null   bool
 11  Social_Comparison_Frequency  4500 non-null   object
 12  Perceived_Stress_Score       4454 non-null   float64
 13  Mental_Health_Index          4500 non-null   int64
 14  Academic_Performance_GPA     4415 non-null   float64
 15  Overall_Impact               4500 non-null   object
dtypes: bool(1), float64(5), int64(1), int8(2), object(7)
memory usage: 470.3+ KB

In [ ]:
df['Mental_Health_Index'].astype('int8')

0       73
1       90
2       70
3       82
4       84
        ..
4495    79
4496    83
4497    73
4498    87
4499    98
Name: Mental_Health_Index, Length: 4500, dtype: int8

In [ ]:
df['Mental_Health_Index'] = df['Mental_Health_Index'].astype('int8')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4500 entries, 0 to 4499
Data columns (total 16 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Student_ID                   4500 non-null   object
 1   Age                          4500 non-null   int8
 2   Gender                       4500 non-null   object
 3   Academic_Level               4500 non-null   object
 4   Primary_Platform             4500 non-null   object
 5   Daily_Usage_Hours            4500 non-null   float64
 6   Weekend_Extra_Hours          4500 non-null   float64
 7   Device_Type                  4500 non-null   object
 8   Sleep_Duration_Hours         4500 non-null   float64
 9   Sleep_Quality_Score          4500 non-null   int8
 10  Late_Night_Usage             4500 non-null   bool
 11  Social_Comparison_Frequency  4500 non-null   object
 12  Perceived_Stress_Score       4454 non-null   float64
 13  Mental_Health_Index          4500 non-null   int8
 14  Academic_Performance_GPA     4415 non-null   float64
 15  Overall_Impact               4500 non-null   object
dtypes: bool(1), float64(5), int8(3), object(7)
memory usage: 439.6+ KB

In [ ]:
df_antes = pd.read_csv('social_media.csv').memory_usage().sum()

In [ ]:
df_antes

np.int64(544632)

In [ ]:
df_depois = df.memory_usage().sum()

In [ ]:
df_depois

np.int64(450132)

In [ ]:
print(f"Uso de memória antes: ")