Importando a biblioteca `pandas` e dando o alias de `pd`

In [ ]:
import pandas as pd

Atribuindo em uma variável `clientes` o arquivo .CSV `clientes.csv`

In [ ]:
clientes = pd.read_csv('clientes.csv')

In [ ]:
clientes

,id_cliente,nome,idade,cidade,estado,categoria,compras_total,data_cadastro,ativo
0,1,Ana Silva,46,Campinas,SP,Bronze,6660.42,2022-01-21,True
1,2,Carlos Oliveira,40,Belo Horizonte,MG,Bronze,7382.57,2022-04-10,True
2,3,Beatriz Santos,39,Belo Horizonte,MG,Bronze,6178.69,2023-02-18,True
3,4,Lucas Rodrigues,50,Salvador,BA,Bronze,4531.72,2024-01-18,True
4,5,Mariana Costa,45,Brasília,DF,Platina,2093.64,2023-11-18,True
5,6,Gabriel Souza,20,Campinas,SP,Ouro,5830.57,2024-04-20,True
6,7,Fernanda Lima,42,Curitiba,PR,Platina,6900.12,2024-02-16,True
7,8,Matheus Alves,37,Rio de Janeiro,RJ,Bronze,5855.25,2023-03-04,True
8,9,Juliana Pereira,31,Belo Horizonte,MG,Bronze,1671.67,2023-01-23,True
9,10,Rodrigo Ferreira,59,Porto Alegre,RS,Prata,411.47,2023-02-06,True
10,11,Camila Ribeiro,27,Rio de Janeiro,RJ,Ouro,5142.46,2024-03-26,True
11,12,Thiago Carvalho,57,Campinas,SP,Ouro,6390.12,2024-05-28,True
12,13,Amanda Gomes,42,Brasília,DF,Bronze,4681.51,2022-02-10,True
13,14,Felipe Martins,42,São Paulo,SP,Platina,6598.24,2023-10-10,True
14,15,Larissa Rocha,34,Belo Horizonte,MG,Ouro,6747.97,2023-01-14,True
15,16,Bruno Barbosa,58,Campinas,SP,Platina,7247.82,2024-02-19,True
16,17,Letícia Dias,40,Campinas,SP,Prata,5710.45,2023-11-15,True
17,18,Diego Nascimento,18,Belo Horizonte,MG,Bronze,8263.80,2023-10-05,True
18,19,Vanessa Moreira,31,Brasília,DF,Prata,4514.82,2022-01-15,True
19,20,Gustavo Mendes,49,Belo Horizonte,MG,Prata,2774.87,2022-04-06,True
20,21,Patrícia Ramos,40,Salvador,BA,Prata,4657.67,2023-06-25,True
21,22,André Freitas,39,Campinas,SP,Ouro,5363.36,2023-07-28,True
22,23,Aline Cardoso,45,Porto Alegre,RS,Ouro,1707.86,2024-03-08,False
23,24,Rafael Teixeira,45,Brasília,DF,Bronze,7722.02,2023-01-20,True
24,25,Isabela Cavalcanti,30,Fortaleza,CE,Ouro,208.05,2023-04-01,True
25,26,Marcelo Castro,50,Salvador,BA,Bronze,2969.09,2024-04-06,True
26,27,Luana Fernandes,58,Recife,PE,Prata,691.85,2023-03-18,False
27,28,Eduardo Duarte,19,Campinas,SP,Ouro,1386.53,2022-03-22,True
28,29,Sofia Monteiro,19,Rio de Janeiro,RJ,Prata,425.97,2024-01-06,False
29,30,Vinícius Correia,19,Belo Horizonte,MG,Prata,3888.99,2023-12-11,True

Outro exemplo de importação de arquivo .csv, dessa vez importando um arquivo interno do Google Colab.

In [ ]:
california_housing = pd.read_csv('/content/sample_data/california_housing_train.csv')

In [ ]:
california_housing

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

---
#Impressões do dataframe.

Impressão das primeiras linhas, por padrão o pandas exibe 5.

In [ ]:
clientes.head()

,id_cliente,nome,idade,cidade,estado,categoria,compras_total,data_cadastro,ativo
0,1,Ana Silva,46,Campinas,SP,Bronze,6660.42,2022-01-21,True
1,2,Carlos Oliveira,40,Belo Horizonte,MG,Bronze,7382.57,2022-04-10,True
2,3,Beatriz Santos,39,Belo Horizonte,MG,Bronze,6178.69,2023-02-18,True
3,4,Lucas Rodrigues,50,Salvador,BA,Bronze,4531.72,2024-01-18,True
4,5,Mariana Costa,45,Brasília,DF,Platina,2093.64,2023-11-18,True

Impressão das últimas linhas, nesse exemplo, as 10 últimas linhas.

In [ ]:
clientes.tail(10)

,id_cliente,nome,idade,cidade,estado,categoria,compras_total,data_cadastro,ativo
20,21,Patrícia Ramos,40,Salvador,BA,Prata,4657.67,2023-06-25,True
21,22,André Freitas,39,Campinas,SP,Ouro,5363.36,2023-07-28,True
22,23,Aline Cardoso,45,Porto Alegre,RS,Ouro,1707.86,2024-03-08,False
23,24,Rafael Teixeira,45,Brasília,DF,Bronze,7722.02,2023-01-20,True
24,25,Isabela Cavalcanti,30,Fortaleza,CE,Ouro,208.05,2023-04-01,True
25,26,Marcelo Castro,50,Salvador,BA,Bronze,2969.09,2024-04-06,True
26,27,Luana Fernandes,58,Recife,PE,Prata,691.85,2023-03-18,False
27,28,Eduardo Duarte,19,Campinas,SP,Ouro,1386.53,2022-03-22,True
28,29,Sofia Monteiro,19,Rio de Janeiro,RJ,Prata,425.97,2024-01-06,False
29,30,Vinícius Correia,19,Belo Horizonte,MG,Prata,3888.99,2023-12-11,True

Exibindo as proporções do dataframe.
> Nesse exemplo, 30 registros em 9 colunas.

In [ ]:
clientes.shape

(30, 9)

Exibindo os tipos de dados presentes no dataframe.

In [ ]:
clientes.dtypes

id_cliente         int64
nome              object
idade              int64
cidade            object
estado            object
categoria         object
compras_total    float64
data_cadastro     object
ativo               bool
dtype: object

Exibindo as informações do dataframe, dentre elas: Número de registros, nome das colunas, tipos de dados em cada coluna, número de registros preenchidos (not-null count).

In [ ]:
clientes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_cliente     30 non-null     int64
 1   nome           30 non-null     object
 2   idade          30 non-null     int64
 3   cidade         30 non-null     object
 4   estado         30 non-null     object
 5   categoria      30 non-null     object
 6   compras_total  30 non-null     float64
 7   data_cadastro  30 non-null     object
 8   ativo          30 non-null     bool
dtypes: bool(1), float64(1), int64(2), object(5)
memory usage: 2.0+ KB

Resumo do dataframe.

In [ ]:
clientes.describe()

       id_cliente      idade  compras_total
count   30.000000  30.000000      30.000000
mean    15.500000  39.033333    4486.985667
std      8.803408  12.260065    2464.756741
min      1.000000  18.000000     208.050000
25%      8.250000  31.000000    2263.947500
50%     15.500000  40.000000    4911.985000
75%     22.750000  45.750000    6546.210000
max     30.000000  59.000000    8263.800000

#Verificação de valores nulos.

Contagem de quantos valores nulos há por coluna.

In [ ]:
clientes.isnull().sum()

id_cliente       0
nome             0
idade            0
cidade           0
estado           0
categoria        0
compras_total    0
data_cadastro    0
ativo            0
dtype: int64

Porcentagem de quantos nulos há por coluna.

In [ ]:
clientes.isnull().mean()

id_cliente       0.0
nome             0.0
idade            0.0
cidade           0.0
estado           0.0
categoria        0.0
compras_total    0.0
data_cadastro    0.0
ativo            0.0
dtype: float64

In [ ]:
california_housing.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
dtype: int64

In [ ]:
california_housing.isnull().mean()

longitude             0.0
latitude              0.0
housing_median_age    0.0
total_rooms           0.0
total_bedrooms        0.0
population            0.0
households            0.0
median_income         0.0
median_house_value    0.0
dtype: float64

In [ ]:
california_housing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   total_bedrooms      17000 non-null  float64
 5   population          17000 non-null  float64
 6   households          17000 non-null  float64
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(9)
memory usage: 1.2 MB

---
Series

In [ ]:
#Criando Series.
risco = pd.Series([0.12, 0.88, 0.45, 0.67], index = ['Ana', 'Bob', 'Cid', 'Dan'], name = 'prob_inadimplencia')

In [ ]:

#A média presente na series.
risco.mean()

np.float64(0.53)

In [ ]:
#O maior número presente na amostra de dados.
risco.max()

0.88

In [ ]:
#Exibe quais indexes são True ou False de acordo com a condição específica.
#Nesse exemplo, qual dos membros tem a probabilidade de inadimplência maior que 0.5.
risco > 0.5

Ana    False
Bob     True
Cid    False
Dan     True
Name: prob_inadimplencia, dtype: bool

In [ ]:
#O sort_values() vai organizar do menor valor ao maior valor, indicando qual membro tem esse valor atribuído.
risco.sort_values()

Ana    0.12
Cid    0.45
Dan    0.67
Bob    0.88
Name: prob_inadimplencia, dtype: float64

In [ ]:
#Vai indicar quantas pessoas possuem o valor presente no dataframe.
risco.value_counts()

prob_inadimplencia
0.12    1
0.88    1
0.45    1
0.67    1
Name: count, dtype: int64

---
DataFrame

In [ ]:
from numpy import nan
#Criando um DataFrame
df = pd.DataFrame({'nome': ['Ana', 'Bob', 'Cid'], 'renda': [5800, 1200, 3200], 'risco': ['Baixo', 'Alto', 'Médio']})

In [ ]:
#Estrutura do DataFrame
df.index

RangeIndex(start=0, stop=3, step=1)

In [ ]:
#Exibe as colunas do DataFrame
df.columns

Index(['nome', 'renda', 'risco'], dtype='object')

In [ ]:
#Exibe s valores de cada integrante do DataFrame.
df.values

array([['Ana', 5800, 'Baixo'],
       ['Bob', 1200, 'Alto'],
       ['Cid', 3200, 'Médio']], dtype=object)

In [ ]:
#Criando uma coluna com base em operações nas colunas existentes.
df['score'] = df['renda'] / 10000
df['aprovado'] = df['risco'] == 'Baixo'

In [ ]:
#Exibindo resultado da coluna Score
df['score']

0    0.58
1    0.12
2    0.32
Name: score, dtype: float64

In [ ]:
#Exibindo resultado da coluna Aprovado
df['aprovado']

0     True
1    False
2    False
Name: aprovado, dtype: bool

In [ ]:
#Exibindo o DataFrame completo, após as alterações.
df

  nome  renda  risco  score  aprovado
0  Ana   5800  Baixo   0.58      True
1  Bob   1200   Alto   0.12     False
2  Cid   3200  Médio   0.32     False

In [ ]:
#Somente uma coluna, é considerada Series.
df['renda']

0    5800
1    1200
2    3200
Name: renda, dtype: int64

In [ ]:
#Quando é mais de uma coluna, já se trata de um DataFrame
df[['renda', 'risco']]

   renda  risco
0   5800  Baixo
1   1200   Alto
2   3200  Médio

In [ ]:
#Localizando elemento por rótulo, nesse exemplo, o elemento 0 da coluna renda.
df.loc[0, 'renda']

np.int64(5800)

In [ ]:
#Localizando os dados das colunas renda e risco.
df.loc[:, 'renda': 'risco']

   renda  risco
0   5800  Baixo
1   1200   Alto
2   3200  Médio

In [ ]:
#iloc serve para Localizar por linha
df.iloc[0, :]

nome          Ana
renda        5800
risco       Baixo
score        0.58
aprovado     True
Name: 0, dtype: object

In [ ]:
#Exibindo as colunas da posição 1 e 2
df.iloc[:, 1:3]

   renda  risco
0   5800  Baixo
1   1200   Alto
2   3200  Médio

In [ ]:
#Executando groupby
g = df.groupby('risco')
g['renda'].mean()
g['renda'].agg(['mean', 'std', 'count'])
g.size()

risco
Alto     1
Baixo    1
Médio    1
dtype: int64

In [ ]:
#Verificando quantos valores ausentes existem
df.isnull().sum()

nome        0
renda       0
risco       0
score       0
aprovado    0
dtype: int64

In [ ]:
#Excluir linhas com valores nulos
df.dropna()

  nome  renda  risco  score  aprovado
0  Ana   5800  Baixo   0.58      True
1  Bob   1200   Alto   0.12     False
2  Cid   3200  Médio   0.32     False

In [ ]:
#Preencher valores nulos da coluna renda usando a média.
df['renda'].fillna(df['renda'].median())

0    5800
1    1200
2    3200
Name: renda, dtype: int64

In [ ]:
#O método ffill vai usar como base o valor anterior e jogará na célula seguinte para não deixar vazia.
df.fillna(method = 'ffill')

/tmp/ipykernel_996/1836459974.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = 'ffill')

  nome  renda  risco  score  aprovado
0  Ana   5800  Baixo   0.58      True
1  Bob   1200   Alto   0.12     False
2  Cid   3200  Médio   0.32     False

---
Otimizando memória convertendo alguns dados para tipos menores

Inicialmente, todos os campos do DataFrame estavam como `float64`, acontece que alguns dados não precisam estar em `float64`, até porque, por exemplo, não existe uma cama e meia.

In [ ]:
california_housing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   total_bedrooms      17000 non-null  float64
 5   population          17000 non-null  float64
 6   households          17000 non-null  float64
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(9)
memory usage: 1.2 MB

In [ ]:
california_housing['population'].describe()

count    17000.000000
mean      1429.573941
std       1147.852959
min          3.000000
25%        790.000000
50%       1167.000000
75%       1721.000000
max      35682.000000
Name: population, dtype: float64

Alterando o tipo do campo `population` para `int16`, levando em consideração que o `int16` aceita até 65555 inserções de dados (além de que não existe uma pessoa e meia, então outro motivo pra não ser necessário o uso do `float64`).

In [ ]:
california_housing['population'] = california_housing['population'].astype('int16')

In [ ]:
california_housing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   total_bedrooms      17000 non-null  float64
 5   population          17000 non-null  int16
 6   households          17000 non-null  float64
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(8), int16(1)
memory usage: 1.1 MB

Alterando o campo `households` para `int16` pelo mesmo motivo, não existe 1 casa e meia.

Fazendo o teste com o `.info()` junto do `.astype('int16')` para verificar quanto de memória iria ser consumida.

In [ ]:
california_housing['households'].astype('int16').info()

<class 'pandas.core.series.Series'>
RangeIndex: 17000 entries, 0 to 16999
Series name: households
Non-Null Count  Dtype
--------------  -----
17000 non-null  int16
dtypes: int16(1)
memory usage: 33.3 KB

In [ ]:
california_housing['households'] = california_housing['households'].astype('int16')

Após essas duas alterações, houve uma melhora considerável de memória, porém, ainda há dados que dariam pra ser convertidos para `int`.

In [ ]:
california_housing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   total_bedrooms      17000 non-null  float64
 5   population          17000 non-null  int16
 6   households          17000 non-null  int16
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(7), int16(2)
memory usage: 996.2 KB

In [ ]:
#Consultando o uso da memória após algumas otimizações.
california_housing.memory_usage()

Index                    132
longitude             136000
latitude              136000
housing_median_age    136000
total_rooms           136000
total_bedrooms        136000
population             34000
households             34000
median_income         136000
median_house_value    136000
dtype: int64

Dando continuidade nas otimizações, o campo `total_bedrooms` também foi convertido para `int16`.

In [ ]:
california_housing['total_bedrooms'] = california_housing['total_bedrooms'].astype('int16')

In [ ]:
california_housing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   total_bedrooms      17000 non-null  int16
 5   population          17000 non-null  int16
 6   households          17000 non-null  int16
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(6), int16(3)
memory usage: 896.6 KB

As duas últimas colunas convertidas foram `total_rooms` e `housing_median_age`, dessas colunas que foram alteradas a única que foi alterada pra `int8` foi `housing_median_age` levando em consideração que o comprimento do campo não passava de 255 caracteres.

In [ ]:
california_housing['total_rooms'] = california_housing['total_rooms'].astype('int16')

In [ ]:
california_housing['housing_median_age'] = california_housing['housing_median_age'].astype('int8')

In [ ]:
california_housing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  int8
 3   total_rooms         17000 non-null  int16
 4   total_bedrooms      17000 non-null  int16
 5   population          17000 non-null  int16
 6   households          17000 non-null  int16
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(4), int16(4), int8(1)
memory usage: 680.8 KB

In [ ]:
california_housing.memory_usage()

Index                    132
longitude             136000
latitude              136000
housing_median_age     17000
total_rooms            34000
total_bedrooms         34000
population             34000
households             34000
median_income         136000
median_house_value    136000
dtype: int64

Relatório da diferença entre o dataframe bruto e o dataframe otimizado.
> Foram feitas otimizações nos campos `households`, `population`, `housing_medium_age`, `total_bedrooms` e `total_rooms`. Os campos citados originalmente estavam como `float`, agora estão como `int`, assim, exigindo menos memória.

In [ ]:
california_bruto = pd.read_csv('/content/sample_data/california_housing_train.csv')
california_antes = california_bruto.memory_usage().sum()

In [ ]:
california_depois = california_housing.memory_usage().sum()

In [ ]:
print(f"Antes: {california_antes} bytes\nDepois: {california_depois} bytes\nA economia foi de: {(((california_antes - california_depois) / california_antes) * 100):.2f}%")

Antes: 1224132 bytes
Depois: 697132 bytes
A economia foi de: 43.05%

---
Convertendo o DataFrame tratado para `.xlsx`

In [ ]:
with pd.ExcelWriter('california_tratado.xlsx') as w:
  california_housing.to_excel(w, sheet_name = 'California')

---
Convertendo o DataFrame tratado para `.json`

In [ ]:
california_housing.to_json('california_tratado.json', orient = 'records', force_ascii = False)

---
Por fim, convertendo o DataFrame tratado para `.csv`.

In [ ]:
california_housing.to_csv('california_tratado.csv')

---
Gerando o `requirements.txt` para guardar as bibliotecas usadas no projeto e suas respectivas versões.

In [ ]:
!pip freeze > requirements.txt